apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  publishNotReadyAddresses: true
  selector:
    {{- include "emqx.selectorLabels" . | nindent 4 }}
  ports:
  - name: mqtt
    port: {{ .Values.service.mqtt }}
    targetPort: mqtt
    protocol: TCP
  - name: mqttssl
    port: {{ .Values.service.mqttssl }}
    targetPort: mqttssl
    protocol: TCP
  - name: ws
    port: {{ .Values.service.ws }}
    targetPort: ws
    protocol: TCP
  - name: wss
    port: {{ .Values.service.wss }}
    targetPort: wss
    protocol: TCP
  - name: dashboard
    port: {{ .Values.service.dashboard }}
    targetPort: dashboard
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "emqx.selectorLabels" . | nindent 4 }}
  ports:
  - name: mqtt
    port: {{ .Values.service.mqtt }}
    targetPort: mqtt
    protocol: TCP
  - name: mqttssl
    port: {{ .Values.service.mqttssl }}
    targetPort: mqttssl
    protocol: TCP
  - name: ws
    port: {{ .Values.service.ws }}
    targetPort: ws
    protocol: TCP
  - name: wss
    port: {{ .Values.service.wss }}
    targetPort: wss
    protocol: TCP
  - name: dashboard
    port: {{ .Values.service.dashboard }}
    targetPort: dashboard
    protocol: TCP
