apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "emqx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "emqx.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "emqx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emqx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: emqx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.emqxConfig }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.envFromSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.envFromSecret }}
        {{- end }}
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: mqttssl
          containerPort: 8883
          protocol: TCP
        - name: ws
          containerPort: 8083
          protocol: TCP
        - name: wss
          containerPort: 8084
          protocol: TCP
        - name: dashboard
          containerPort: 18083
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: emqx-data
          mountPath: /opt/emqx/data
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: emqx-data
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
