apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-config
  namespace: zigbee2mqtt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: zigbee2mqtt
    kind: ConfigMap
    creationPolicy: Owner
  data:
    - secretKey: configuration.yaml
      remoteRef:
        key: zigbee2mqtt-config
