apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-config
  namespace: zigbee2mqtt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: zigbee2mqtt
    kind: ConfigMap
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        configuration.yaml: "{{ .zigbee2mqttConfig | toYaml | indent 0 }}"
  data:
    - secretKey: zigbee2mqttConfig
      remoteRef:
        key: zigbee2mqtt-config
