apiVersion: v1
kind: Service
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: web
    protocol: TCP
    name: web
  selector:
    app: zigbee2mqtt
