---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-healthchecks-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: alertmanager-healthchecks-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        ping-url: '{{ `{{ .pingurl }}` }}'
  data:
  - secretKey: pingurl
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: alertmanager-healthchecks
      property: ping-url
