---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: alertmanager-pushover-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        user-key: '{{ `{{ .userkey }}` }}'
        api-token: '{{ `{{ .apitoken }}` }}'
  data:
  - secretKey: userkey
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: pushover-credentials
      property: username
  - secretKey: apitoken
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: pushover-credentials
      property: password
