replicaCount: 3
image:
  repository: emqx/emqx
  pullPolicy: IfNotPresent
  tag: "6.1.0"

podManagementPolicy: Parallel

persistence:
  enabled: true
  size: 10Gi
  storageClassName: longhorn-standard
  accessMode: ReadWriteOnce

emqxConfig:
  EMQX_CLUSTER__DISCOVERY_STRATEGY: dns

externalSecrets:
  enabled: true
  items:
  - name: emqx-dashboard-secret
    secretStoreRef: onepassword-connect
    templateData:
      EMQX_DASHBOARD__DEFAULT_USERNAME:
        value: admin
        isSecret: false
    data:
    - remoteKey: emqx-dashboard-password
      secretKey: EMQX_DASHBOARD__DEFAULT_PASSWORD

envFromSecret: "emqx-dashboard-secret"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  clusterIP: None
  mqtt: 1883
  mqttssl: 8883
  ws: 8083
  wss: 8084
  dashboard: 18083
  externalTrafficPolicy: "Cluster"

httproutes:
- enabled: true
  name: emqx-dashboard-httproute
  namespace: emqx
  hostname: emqx.app.damman.tech
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  path: /
  backend:
    name: emqx
    port: 18083

metrics:
  enabled: false
  type: prometheus
