{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: lucidvault
    app.kubernetes.io/component: secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ .name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteKey }}
      property: {{ .property }}
  {{- end }}
{{- end }}
