apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter-secret
  namespace: monitoring
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: pve-exporter-secret
    creationPolicy: Owner
  data:
    - secretKey: tokenName
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Proxmox - Monitoring Account
        metadataPolicy: None
        property: token_name
    - secretKey: tokenValue
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Proxmox - Monitoring Account
        metadataPolicy: None
        property: token_value
