apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-exporter-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: pve-exporter-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: Proxmox - Monitoring Account
      property: username
  - secretKey: token-name
    remoteRef:
      key: Proxmox - Monitoring Account
      property: token-name
  - secretKey: token-value
    remoteRef:
      key: Proxmox - Monitoring Account
      property: token-value
