apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: pve-exporter-credentials
    creationPolicy: Owner
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: Proxmox - Monitoring Account
      metadataPolicy: None
      property: username
    secretKey: PVE_USER
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: Proxmox - Monitoring Account
      metadataPolicy: None
      property: api_key
    secretKey: PVE_TOKEN_NAME
