apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: monitoring
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9221
      protocol: TCP
      name: metrics
  selector:
    app: pve-exporter
