prometheus-pve-exporter:
  replicaCount: 1

  env:
    pveAuthType: "token"
    pveUser: "monitoring@pve"
    pveTokenName: "prometheus"
    pveTokenValue: ""
    pveExistingSecretName: "pve-exporter-secret"
    pveVerifySsl: false

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    type: ClusterIP
    port: 80

  serviceMonitor:
    enabled: false
