prometheus-pve-exporter:
  replicaCount: 1

  env:
    pveAuthType: "token"
    pveUser: "monitoring@pve"
    pveTokenName: "prometheus"
    pveTokenValue: ""
    pveExistingSecretName: "pve-exporter-secret"
    pveVerifySsl: false

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  service:
    type: ClusterIP
    port: 80

  serviceMonitor:
    enabled: true
    interval: 60s
    additionalLabels:
      release: prometheus
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: prometheus-pve-exporter:80
    pveTargets:
      - 10.0.10.200
      - 10.0.10.201
