apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubelet-csr-approver
  namespace: kubelet-serving-cert-approver
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet-csr-approver
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubelet-serving-cert-approver
  namespace: kubelet-serving-cert-approver
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet-serving-cert-approver
