# cert-manager values
# Docs: https://cert-manager.io/docs/

# CRDs
crds:
  enabled: true
  keep: true

# Controller
replicaCount: 2

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

extraArgs:
  - --enable-gateway-api
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 5m
    memory: 32Mi

podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"

# Prometheus metrics
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    labels:
      release: prometheus

# Webhook
webhook:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 5m
      memory: 16Mi

# CA Injector
cainjector:
  enabled: true
  replicaCount: 1
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 32Mi

# Startup API Check
startupapicheck:
  enabled: true
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
