apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: homarr
  labels:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/component: web
