---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: github-client-secret
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: argocd
          app.kubernetes.io/part-of: argocd
      data:
        dex.github.clientSecret: '{{ `{{ .clientSecret }}` }}'
  data:
  - secretKey: clientSecret
    remoteRef:
      key: github-client-secrets
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None