apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/component: web
data:
  settings.yaml: |
{{ .Values.config.settingsYaml | indent 4 }}
  bookmarks.yaml: |
{{ .Values.config.bookmarksYaml | indent 4 }}
  widgets.yaml: |
{{ .Values.config.widgetsYaml | indent 4 }}
  services.yaml: |
{{ .Values.config.servicesYaml | indent 4 }}
  docker.yaml: |
{{ .Values.config.dockerYaml | indent 4 }}
  kubernetes.yaml: |
{{ .Values.config.kubernetesYaml | indent 4 }}
  custom.css: |
{{ .Values.config.customCss | indent 4 }}
  custom.js: |
{{ .Values.config.customJs | indent 4 }}
