---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-authentik-outpost-token
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.authentikOutpost.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: homepage-authentik-outpost-token
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.authentikOutpost.externalSecret.remoteKey }}
      property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.widgetSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
  data:
  - secretKey: HOMEPAGE_VAR_PROXMOX_USER
    remoteRef:
      key: {{ .Values.widgetSecrets.proxmox.remoteKey }}
      property: username
  - secretKey: HOMEPAGE_VAR_PROXMOX_PASSWORD
    remoteRef:
      key: {{ .Values.widgetSecrets.proxmox.remoteKey }}
      property: password
  - secretKey: HOMEPAGE_VAR_ADGUARD_USER
    remoteRef:
      key: {{ .Values.widgetSecrets.adguard.remoteKey }}
      property: username
  - secretKey: HOMEPAGE_VAR_ADGUARD_PASSWORD
    remoteRef:
      key: {{ .Values.widgetSecrets.adguard.remoteKey }}
      property: password
