apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-authentik-outpost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/component: authentik-outpost
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/component: authentik-outpost
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
        app.kubernetes.io/component: authentik-outpost
    spec:
      containers:
      - name: authentik-proxy
        image: "{{ .Values.authentikOutpost.image.repository }}:{{ .Values.authentikOutpost.image.tag }}"
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
        env:
        - name: AUTHENTIK_HOST
          value: "{{ .Values.authentikOutpost.authentikHost }}"
        - name: AUTHENTIK_HOST_BROWSER
          value: "{{ .Values.authentikOutpost.authentikHostBrowser }}"
        - name: AUTHENTIK_INSECURE
          value: "false"
        - name: AUTHENTIK_TOKEN
          valueFrom:
            secretKeyRef:
              name: homepage-authentik-outpost-token
              key: token
        resources:
          {{- toYaml .Values.authentikOutpost.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /outpost.goauthentik.io/ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 6
