image:
  repository: koenkk/zigbee2mqtt
  tag: "2.12.1@sha256:80f7f04f72a99e4c4ef51ef7e98ee736edba6db0ecbb7abc626d0c4b0f1871f1"

service:
  type: ClusterIP

namespaceLabels:
  gateway.damman.tech/svc-gateway: "true"

networkPolicy:
  cilium:
    enabled: true
  prometheusNamespace: monitoring
  mqttNamespace: emqx
  extraEgress:
  - toEntities:
    - world
    toPorts:
    - ports:
      - port: "6638"
        protocol: TCP

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  size: 2Gi
  storageClassName: longhorn-standard

authentikOutpost:
  enabled: true
  image:
    repository: ghcr.io/goauthentik/proxy
    tag: "2026.5.4"
  authentikHost: "http://authentik-server.authentik.svc"
  authentikHostBrowser: "https://sso.app.damman.tech"
  externalSecret:
    enabled: true
    secretStoreRef: onepassword-connect
    remoteKey: authentik-outpost-zigbee2mqtt

externalSecrets:
  enabled: true
  items:
  - name: zigbee2mqtt-config
    secretStoreRef: onepassword-connect
    remoteKey: zigbee2mqtt-config
    secretKey: configuration.yaml

httproutes:
- enabled: true
  name: zigbee-httproute
  namespace: zigbee2mqtt
  hostname: zigbee.svc.damman.tech
  path: /
  gateway:
    name: svc-gateway
    namespace: kube-system
    sectionName: svc-https-listener
  backend:
    name: zigbee2mqtt-authentik-outpost
    port: 9000
