image:
  tag: 2.6.2

service:
  type: ClusterIP

secretesMigratorContainer:
  repository: mikefarah/yq
  tag: 4.40.5

configmap:
  enabled: true

statefulset:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  storage:
    enabled: true
    size: 2Gi
    storageClassName: longhorn-standard
  secrets:
    name: zigbee2mqtt-config

httproutes:
- enabled: true
  name: zigbee-httproute
  namespace: zigbee2mqtt
  hostname: zigbee.app.damman.tech
  path: /
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  backend:
    name: zigbee2mqtt
    port: 8080
