---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: argocd-apps
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: argocd-gitops
    homelab.damman.tech/tier: tier-0
    homelab.damman.tech/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm/
    chart: argocd-apps
    targetRevision: 2.0.5
    helm:
      values: |
        projects:
          operators:
            namespace: argocd
            displayName: Operators
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            clusterResourceWhitelist:
              - group: '*'
                kind: '*'
            destinations:
              - namespace: '*'
                server: '*'
            sourceRepos:
              - '*'
          apps:
            namespace: argocd
            displayName: Apps
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            clusterResourceWhitelist:
              - group: '*'
                kind: '*'
            destinations:
              - namespace: '*'
                server: '*'
            sourceRepos:
              - '*'
          infrastructure:
            namespace: argocd
            displayName: infrastructure
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            clusterResourceWhitelist:
              - group: '*'
                kind: '*'
            destinations:
              - namespace: '*'
                server: '*'
            sourceRepos:
              - '*'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
