---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: security-infrastructure
    homelab.damman.tech/tier: tier-2
    homelab.damman.tech/managed-by: argocd
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
  - repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.5.4
    helm:
      valueFiles:
      - $values/resources/gitops-config/operators/authentik/values.yaml
  - repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/operators/authentik
    ref: values
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
