---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: certificate-management
    app.kubernetes.io/part-of: security-infrastructure
    homelab.damman.tech/tier: tier-1
    homelab.damman.tech/managed-by: argocd
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
    - repoURL: https://charts.jetstack.io/
      chart: cert-manager
      targetRevision: v1.19.2
      helm:
        valueFiles:
        - $values/resources/gitops-config/operators/cert-manager/values.yaml
    - repoURL: https://github.com/TheIronRock95/homelab-config
      targetRevision: HEAD
      path: resources/gitops-config/operators/cert-manager
      ref: values
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
