---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: homelab-infrastructure
    homelab.damman.tech/tier: tier-1
    homelab.damman.tech/managed-by: argocd
  name: cloudnative-pg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
  - repoURL: https://cloudnative-pg.io/charts/
    chart: cloudnative-pg
    targetRevision: 0.27.0
    helm:
      valueFiles:
      - $values/resources/gitops-config/operators/cloudnative-pg/values.yaml
  - repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/operators/cloudnative-pg
    ref: values
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
