---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: cluster-config
    app.kubernetes.io/component: cluster-config
    app.kubernetes.io/part-of: homelab-infrastructure
    homelab.damman.tech/tier: tier-0
    homelab.damman.tech/managed-by: argocd
  name: cluster-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    repoURL: https://github.com/wouterdamman/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/operators/cluster-config
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
