---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: homelab-infrastructure
    homelab.damman.tech/tier: tier-1
    homelab.damman.tech/managed-by: argocd
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
  - repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.20.0
    helm:
      valueFiles:
      - $values/resources/gitops-config/operators/external-dns/values.yaml
  - repoURL: 'https://github.com/TheIronRock95/homelab-config'
    path: resources/gitops-config/operators/external-dns
    targetRevision: HEAD
    ref: values
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
