---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: secrets-management
    homelab.damman.tech/tier: tier-1
    homelab.damman.tech/managed-by: argocd
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.3.2
      helm:
        valueFiles:
          - $values/resources/gitops-config/operators/external-secrets/values.yaml
    - repoURL: https://github.com/TheIronRock95/homelab-config
      targetRevision: HEAD
      path: resources/gitops-config/operators/external-secrets
      ref: values
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
