---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
  - repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      valueFiles:
      - $values/resources/gitops-config/operators/external-dns/values.yaml
  - repoURL: 'https://github.com/TheIronRock95/homelab-config'
    path: resources/gitops-config/operators/external-dns
    targetRevision: HEAD
    ref: values
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
