---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/name: firefly-iii
    app.kubernetes.io/component: finance
    app.kubernetes.io/part-of: personal-productivity
    homelab.damman.tech/tier: tier-4
    homelab.damman.tech/managed-by: argocd
  name: firefly-iii
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/applications/firefly-iii
  destination:
    namespace: firefly-iii
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
