---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: home-automation
    app.kubernetes.io/part-of: smart-home
    homelab.damman.tech/tier: tier-3
    homelab.damman.tech/managed-by: argocd
  name: home-assistant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
  - repoURL: https://sironite.github.io/helm-home-assistant
    chart: home-assistant
    targetRevision: "2.0.2"
    helm:
      valueFiles:
      - $values/resources/gitops-config/applications/home_assistant/values.yaml
  - repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    ref: values
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates
    - /spec/template/spec/containers/0/resources/limits/cpu
    - /spec/template/spec/containers/1/resources/limits/cpu
