---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: home-automation
    app.kubernetes.io/part-of: smart-home
    homelab.damman.tech/tier: tier-3
    homelab.damman.tech/managed-by: argocd
  name: home-assistant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/applications/home_assistant
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
