---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: observability-stack
    homelab.damman.tech/tier: tier-2
    homelab.damman.tech/managed-by: argocd
  name: loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.49.0
    helm:
      valueFiles:
      - $values/resources/gitops-config/operators/loki/values.yaml
  - repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/operators/loki
    ref: values
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
