---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/name: lucidvault
    app.kubernetes.io/component: ai-tools
    app.kubernetes.io/part-of: productivity
    homelab.damman.tech/tier: tier-3
    homelab.damman.tech/managed-by: argocd
  name: lucidvault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/TheIronRock95/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/applications/lucidvault
  destination:
    namespace: lucidvault
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
