apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pve-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/TheIronRock95/homelab-config.git
    path: resources/gitops-config/infrastructure/prometheus-pve-exporter
    targetRevision: main
    helm:
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
