---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: prometheus-community
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: observability-stack
    homelab.damman.tech/tier: tier-2
    homelab.damman.tech/managed-by: argocd
  name: prometheus-community
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 87.15.1
    helm:
      valueFiles:
      - $values/resources/gitops-config/operators/prometheus-community/values.yaml
  - repoURL: https://github.com/wouterdamman/homelab-config
    targetRevision: HEAD
    path: resources/gitops-config/operators/prometheus-community
    ref: values
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
