apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pve-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: prometheus-pve-exporter
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: observability-stack
    homelab.damman.tech/tier: tier-2
    homelab.damman.tech/managed-by: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/wouterdamman/homelab-config.git
    path: resources/gitops-config/infrastructure/prometheus-pve-exporter
    targetRevision: main
    helm:
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
