---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: sync-app
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: argocd-gitops
    homelab.damman.tech/tier: tier-0
    homelab.damman.tech/managed-by: argocd
  name: sync-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wouterdamman/homelab-config
    path: resources/gitops-config/sync-app/templates/
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      