image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2026.1.2
  pullPolicy: IfNotPresent

env:
- name: TZ
  value: Europe/Amsterdam

service:
  type: LoadBalancer
  port: 8123
  annotations:
    io.cilium/lb-ipam-ips: "10.0.10.243"
  loadBalancerIP: 10.0.10.243

ingress:
  enabled: false

hostNetwork: true

dnsPolicy: ClusterFirstWithHostNet

persistence:
  enabled: true
  size: 10Gi
  storageClassName: longhorn-standard

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

addons:
  codeserver:
    enabled: true
    service:
      type: ClusterIP
      port: 12321
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

externalSecrets:
  enabled: true
  items:
  - name: homeassistant-secrets
    secretStoreRef: onepassword-connect
    remoteKey: homeassistant-secrets
    secretKey: secrets.yaml

httproutes:
- enabled: true
  name: ha-httproute
  namespace: home-assistant
  hostname: ha.app.damman.tech
  path: /
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  backend:
    name: home-assistant
    port: 8123

- enabled: true
  name: codeserver-httproute
  namespace: home-assistant
  hostname: codeserver.app.damman.tech
  path: /
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  backend:
    name: home-assistant-codeserver
    port: 12321
