---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: authentik-secret-key
    template:
      engineVersion: v2
      type: Opaque
      data:
        secret-key: '{{ "{{ .secretKey }}" }}'
  data:
  - secretKey: secretKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: authentik-secret-key
      metadataPolicy: None
      property: secret-key
