---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-s3-backup-credentials
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: longhorn-s3-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: '{{ .keyid }}'
        AWS_SECRET_ACCESS_KEY: '{{ .secretkey }}'
        AWS_ENDPOINTS: 'https://s3.eu-central-003.backblazeb2.com'
  data:
  - secretKey: keyid
    remoteRef:
      key: longhorn-s3-backup
      property: AWS_ACCESS_KEY_ID
  - secretKey: secretkey
    remoteRef:
      key: longhorn-s3-backup
      property: AWS_SECRET_ACCESS_KEY
