---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-s3-backup-credentials
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: longhorn-s3-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: '{{ .awsAccessKeyId }}'
        AWS_SECRET_ACCESS_KEY: '{{ .awsSecretAccessKey }}'
        AWS_ENDPOINTS: '{{ .awsEndpoints }}'
  data:
  - secretKey: awsAccessKeyId
    remoteRef:
      key: longhorn-s3-backup
      property: AWS_ACCESS_KEY_ID
  - secretKey: awsSecretAccessKey
    remoteRef:
      key: longhorn-s3-backup
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: awsEndpoints
    remoteRef:
      key: longhorn-s3-backup
      property: AWS_ENDPOINTS
