---
# Superuser credentials for cnpg-homeassistant cluster
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-homeassistant-superuser-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-homeassistant-superuser
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  data:
  - secretKey: username
    remoteRef:
      key: cnpg-homeassistant-superuser
      property: username
  - secretKey: password
    remoteRef:
      key: cnpg-homeassistant-superuser
      property: password
---
# Home Assistant application user credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-homeassistant-app-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-homeassistant-app
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  data:
  - secretKey: username
    remoteRef:
      key: cnpg-homeassistant-app
      property: username
  - secretKey: password
    remoteRef:
      key: cnpg-homeassistant-app
      property: password
