---
# Superuser credentials for cnpg-shared cluster
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-shared-superuser-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-shared-superuser
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  data:
  - secretKey: username
    remoteRef:
      key: cnpg-shared-superuser
      property: username
  - secretKey: password
    remoteRef:
      key: cnpg-shared-superuser
      property: password
---
# Authelia database user credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-shared-authelia-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-shared-authelia
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  data:
  - secretKey: username
    remoteRef:
      key: cnpg-shared-authelia
      property: username
  - secretKey: password
    remoteRef:
      key: cnpg-shared-authelia
      property: password
---
# NetBox database user credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-shared-netbox-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-shared-netbox
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  data:
  - secretKey: username
    remoteRef:
      key: cnpg-shared-netbox
      property: username
  - secretKey: password
    remoteRef:
      key: cnpg-shared-netbox
      property: password
