---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-validation-pushover
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-backup-validation-pushover
    template:
      engineVersion: v2
      type: Opaque
      data:
        user-key: "{{`{{ .userkey }}`}}"
        api-token: "{{`{{ .apitoken }}`}}"
  data:
  - secretKey: userkey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: cnpg-pushover-credentials
      property: username
  - secretKey: apitoken
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: cnpg-pushover-credentials
      property: password
