---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: cnpg-s3-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
        ACCESS_KEY_ID: '{{ `{{ .keyid }}` }}'
        ACCESS_SECRET_KEY: '{{ `{{ .secretkey }}` }}'
  data:
  - secretKey: keyid
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnpg-s3-backup
      metadataPolicy: None
      property: username
  - secretKey: secretkey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnpg-s3-backup
      metadataPolicy: None
      property: password
