{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ default "onepassword-connect" .secretStoreRef }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
  - remoteRef:
      key: {{ .remoteKey }}
    secretKey: {{ .secretKey }}
{{- end }}
{{- end }}
