apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
---
{{- if .Values.addons.codeserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}-codeserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: codeserver
spec:
  type: {{ .Values.addons.codeserver.service.type }}
  ports:
  - name: codeserver
    port: {{ .Values.addons.codeserver.service.port }}
    targetPort: 8443
    protocol: TCP
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
{{- end }}
