apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "home-assistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
