{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: evcc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ default "onepassword-connect" .secretStoreRef }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
    {{- if .templateData }}
    template:
      engineVersion: v2
      type: Opaque
      data:
        {{- range $key, $item := .templateData }}
        {{- if $item.isSecret }}
        {{ $key }}: '{{ `{{ .` }}{{ $item.value }}{{ ` }}` }}'
        {{- else }}
        {{ $key }}: "{{ $item.value }}"
        {{- end }}
        {{- end }}
    {{- end }}
  data:
    {{- range .data }}
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
        metadataPolicy: None
      secretKey: {{ .secretKey }}
    {{- end }}
{{- end }}
{{- end }}
