apiVersion: v1
kind: Namespace
metadata:
  name: evcc
  labels:
    name: evcc
    app.kubernetes.io/name: evcc
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    gateway.damman.tech/app-gateway: "true"
