apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evcc-data
  namespace: evcc
  labels:
    app.kubernetes.io/name: evcc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
