{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: netbox
spec:
  secretStoreRef:
    name: {{ .secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
    template:
      engineVersion: v2
      data:
        {{- range $key, $value := .templateData }}
        {{ $key }}: '{{ `{{ .` }}{{ $value.secretKey }}{{ ` }}` }}'
        {{- end }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
