installCRDs: false

# Controller (main component)
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# Webhook
webhook:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 32Mi
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true

# Cert Controller
certController:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 32Mi
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true

# Prometheus metrics
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
