cluster:
  name: talos
  id: 1

kubeProxyReplacement: true

# Talos specific
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent: [ CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID ]
    cleanCiliumState: [ NET_ADMIN, SYS_ADMIN, SYS_RESOURCE ]

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# https://docs.cilium.io/en/stable/network/concepts/ipam/
ipam:
  mode: kubernetes

operator:
  rollOutPods: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

#debug:
#  enabled: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 200

l2announcements:
  enabled: true

externalIPs:
  enabled: true

bpf:
  masquerade: true
  tproxy: true

loadBalancer:
  # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#maglev-consistent-hashing
  algorithm: maglev

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

envoy:
  # 0 disables stream idle timeout (default 300s kills WebSocket connections after 5min background)
  streamIdleTimeoutDurationSeconds: 0
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [ NET_ADMIN, PERFMON, BPF ]
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingressController:
  enabled: false
  # default: true
  # loadbalancerMode: shared
  # service:
  #   annotations:
  #     io.cilium/lb-ipam-ips: 10.0.10.240

hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 32Mi
  ui:
    enabled: true
    rollOutPods: true
    backend:
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 5m
          memory: 32Mi
    frontend:
      resources:
        limits:
          cpu: 50m
          memory: 32Mi
        requests:
          cpu: 2m
          memory: 16Mi
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - http
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus

# Prometheus metrics for Cilium agent and operator
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus

